title: "Software Vedas"
description: "The Gita Saar of all Software Wisdom."

# ✅ Project Pages settings
url: "https://Aryavarta-Labs.github.io"
baseurl: "/Software-Vedas"   # keep the leading slash, no trailing slash

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

# Collections (posts is built-in; define the others)
collections:
  products:
    output: true
    permalink: /products/:name/
  posts:
    output: true
    permalink: /posts/:name/
  articles:
    output: true
    permalink: /articles/:name/
  codes:
    output: true
    permalink: /codes/:name/
