title: "Software Vedas"
description: "Insights on Product Development, Systems Design, and DSA"
baseurl: "" 
url: "https://Aryavarta-Labs.github.io/Software-Vedas"

theme: minima

collections:
  posts:
    output: true
    permalink: /posts/:title/
  articles:
    output: true
    permalink: /articles/:title/
  codes:
    output: true
    permalink: /codes/:title/
