title: "Software Vedas"
subtitle: "For software professionals."
description: "The Gita Saar of all Software Wisdom."

# ✅ Project Pages settings
url: "https://Aryavarta-Labs.github.io"
baseurl: "/Software-Vedas"   # keep the leading slash, no trailing slash

theme: minima
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed

# ✅ Navbar pages (in order)
header_pages:
  - index.md
  - articles.md
  - codes.md
  - posts.md
  - products.md

# ✅ Collections
collections:
  posts:
    output: true
    permalink: /posts/:name/
  products:
    output: true
    permalink: /products/:name/
  articles:
    output: true
    permalink: /articles/:name/
  codes:
    output: true
    permalink: /codes/:name/
