title: "Software Vedas"
description: "Insights on Product Development, Systems Design, and DSA"

# ✅ Project Pages settings
url: "https://Aryavarta-Labs.github.io"
baseurl: "/Software-Vedas"   # keep the leading slash, no trailing slash

theme: minima
markdown: kramdown

# Collections (posts is built-in; define the others)
collections:
  articles:
    output: true
    permalink: /articles/:name/
  codes:
    output: true
    permalink: /codes/:name/
  products:
    output: true
    permalink: /products/:name/
